### PR TITLE
Create CPDAcknowledgements.h

### PR DESCRIPTION
**Pull request by ladland**
Created Umbrella Header to allow for Swift ModuleMap Creation.

ModuleMap creation required to allow the pod to be used in Swift projects

### CODE REVIEW

**Comment by orta** [comment]
Weird, I thought CococaPods generates these for you? @CocoaPods/core can anyone confirm? If not, merge away 👍

**Comment by segiddins** [comment]
Cocoapods should be generating an umbrella header that imports all public headers

**Comment by orta** [comment]
Then this shouldn't be needed, @ladland any chance you can show a sample project that is broken?

**Comment by ladland** [comment]
I looks like it was an issue with the download.
I removed and re-added the Pod and the project compiled.
I am closing the request as no longer required

**Comment by orta** [comment]
👍 cool beans - thanks for trying to help @ladland!

**Pull request closed without merging**
